config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :definitions
    resources :definition_votes
    resources :definition_vote_ups
    resources :definition_vote_downs
    resources :definition_tags
    resources :tags
    resources :unknown_words

    root to: "users#index"
  end
  devise_for :users,
             path: "auth",
             path_names: { sign_up: "signup", sign_in: "login", sign_out: "logout" },
             controllers: { sessions: "users/sessions",
                            passwords: "users/passwords",
                            registrations: "users/registrations",
                            confirmations: "users/confirmations" }

  namespace :v1 do
    # TODO: make API endpoints for future mobile development
  end

  resource :user, only: :show
  resources :words, only: :index
  resources :definitions, only: %i[new create edit update destroy] do
    resources :votes, only: :create, module: :definitions
  end
  resources :tags, only: %i[index show]
  resources :unknown_words, only: %i[index new create]

  get "initials/:initial", to: "initials#show", constraints: { initial: /\w/ }, as: :initial

  root to: "words#index"
end

app/views/shared/_alphabet.html.slim
.d-flex.flex-wrap
  - ("A".."Z").to_a.each do |initial|
    = active_link_to initial, initial_path(initial), active: :exact, active_disable: true,
      class: "btn btn-outline-secondary mr-1 mb-1"

app/views/shared/_definition.html.slim
/ required locals: definition
.card.mb-1
  .card-body
    h5.card-title
      = definition.word
    p.card-text
      = definition.definition
    p.card-text
      i = definition.example
    p.card-text
      - definition.tags.each do |tag|
        = link_to tag do
          span.badge.badge-dark.mr-1 = tag.name
    p.card-text
      b by #{definition.author_name} #{time_ago_in_words(definition.created_at)} ago

    div[style="display:flex"]
      div[style="flex:2" class="js-VotingThumbs" data-definition-id="#{definition.id}"]
        = render "shared/voting_thumbs", definition: definition

      - if policy(definition).edit?
        = link_to "Edit", edit_definition_path(definition), class: "card-link"

app/views/shared/_voting_thumbs.html.slim
/ required locals: definition
ruby:
  upvoted = current_user&.upvotes&.include?(definition.id) == true
  upvote_link_url = policy(definition).vote? ? definition_votes_path(definition, type: :up) : "javascript:void(0)"
  upvote_link_options = policy(definition).vote? ? {
    method: :post,
    remote: true,
    class: "dcd-Thumbs dcd-Thumbs-up js-VotingThumbs-up",
    "data-user-vote" => upvoted
  } : {
    class: "dcd-Thumbs dcd-Thumbs-up",
    style: "pointer-events:none"
  }

  downvoted = current_user&.downvotes&.include?(definition.id) == true
  downvote_link_url = policy(definition).vote? ? definition_votes_path(definition, type: :down) : "javascript:void(0)"
  downvote_link_options = policy(definition).vote? ? {
    method: :post,
    remote: true,
    class: "dcd-Thumbs dcd-Thumbs-down js-VotingThumbs-down",
    "data-user-vote" => downvoted
  } : {
    class: "dcd-Thumbs dcd-Thumbs-down",
    style: "pointer-events:none"
  }

= link_to upvote_link_url, upvote_link_options do
  i[class="dcd-SvgIcon dcd-SvgIcon-upvote"]
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34 34"><path d="M34 15.3c0-1.9-1.4-3.4-3.1-3.4h-9.7l1.5-7.8v-.5c0-.7-.3-1.4-.6-1.9L20.4 0 10.2 11.2c-.6.5-.9 1.4-.9 2.4v17c0 1.9 1.4 3.4 3.1 3.4h13.9c1.2 0 2.3-.8 2.8-2l4.6-12.1c.2-.3.2-.9.2-1.2v-3.4h.1c0 .2 0 0 0 0zM0 34h6.2V13.6H0V34z"></path></svg>
  span.dcd-Thumbs-count
    = definition.definition_vote_ups_count

= link_to downvote_link_url, downvote_link_options do
  i[class="dcd-SvgIcon dcd-SvgIcon-downvote"]
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34 34"><path d="M27.8 0v20.4H34V0h-6.2zm-6.2 0H7.7C6.5 0 5.4.9 4.9 2L.3 14.1c-.1.3-.3.7-.3 1.2v3.4c0 1.9 1.4 3.4 3.1 3.4h9.7l-1.5 7.8v.5c0 .7.3 1.4.6 1.9l1.7 1.7 10.2-11.2c.6-.7.9-1.5.9-2.4v-17c0-1.9-1.4-3.4-3.1-3.4z"></path></svg>
  span.dcd-Thumbs-count
    = definition.definition_vote_downs_count

span.ml-1.text-muted = definition.score