config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :definitions
    resources :definition_votes
    resources :definition_vote_ups
    resources :definition_vote_downs
    resources :definition_tags
    resources :tags
    resources :unknown_words

    root to: "users#index"
  end
  devise_for :users,
             path: "auth",
             path_names: { sign_up: "signup", sign_in: "login", sign_out: "logout" },
             controllers: { sessions: "users/sessions",
                            passwords: "users/passwords",
                            registrations: "users/registrations",
                            confirmations: "users/confirmations" }

  namespace :v1 do
    # TODO: make API endpoints for future mobile development
  end

  resource :user, only: :show
  resources :words, only: :index
  resources :definitions, only: %i[new create edit update destroy] do
    resources :votes, only: :create, module: :definitions
  end
  resources :tags, only: %i[index show]
  resources :unknown_words, only: %i[index new create]

  get "initials/:initial", to: "initials#show", constraints: { initial: /\w/ }, as: :initial

  root to: "words#index"
end

app/controllers/v1/words_controller.rb
# frozen_string_literal: true

module V1
  class WordsController < V1::ApplicationController
    def index; end

    def show; end
  end
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  # GET    /words?q=WIP&tag=tech
  def index
    @q = params[:q]
    @tag = params[:tag]

    rows = Definition::Search.call(q: params[:q], tag: params[:tag])
    @definitions = Kaminari.paginate_array(rows).page(params[:page]).per(10)
  end
end

app/views/words/index.html.slim
- provide(:title, "Words")
- provide(:top_left_link) do
  = link_to "Full List of Words", initial_path("A")

= form_with url: words_path, method: :get, local: true, html: { class: "mb-3 WordSearch" } do |f|
  .WordSearch-searchBar.mb-2
    label.WordSearch-searchBar-label[for="#q"]
      i.fa.fa-search[aria-hidden="true"]
    = f.text_field :q, value: @q,
      class: "WordSearch-searchBar-input js-WordSearch-searchBar-input form-control",
      list: "WordSearch-searchBar-wordOptions",
      placeholder: "Type a word to search"
    datalist#WordSearch-searchBar-wordOptions
      = options_for_select(Definition.distinct.pluck(:word))
    = active_link_to words_path(q: "", tag: @tag), active: :exact, active_disable: true, class: "WordSearch-searchBar-cancel" do
      i.fa.fa-times-circle

  .WordSearch-tagFilter
    label.WordSearch-tagFilter-label[for="#tag"]
      = active_link_to tags_path, active: :exact, active_disable: true, title: "All Tags" do
        i.fa.fa-tag[aria-hidden="true"]
    = f.select :tag,
      options_for_select(Tag.pluck(:name), @tag),
      { include_blank: true },
      { class: "mx-2 WordSearch-tagFilter-select js-WordSearch-tagFilter-select" }
    = active_link_to words_path(q: @q, tag: ""), active: { tag: "" }, active_disable: true, title: "Clear Tag Filter"  do
      i.fa.fa-times-circle

  / Hidden submit button that is pressed programmatically by JS.
  input[type="submit" style="display:none" class="WordSearch-submit js-WordSearch-submit"]

- @definitions.each do |definition|
  - cache definition
    = render "shared/definition", definition: definition

= paginate @definitions

hr

= render "shared/alphabet"

hr

= active_link_to "Register Undefined Word", new_unknown_word_path, active: :exact, active_disable: true
br/
= active_link_to "All Undefined Words", unknown_words_path, active: :exact, active_disable: true
br/
= active_link_to "Create Definition", new_definition_path, active: :exact, active_disable: true