config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :definitions
    resources :definition_votes
    resources :definition_vote_ups
    resources :definition_vote_downs
    resources :definition_tags
    resources :tags
    resources :unknown_words

    root to: "users#index"
  end
  devise_for :users,
             path: "auth",
             path_names: { sign_up: "signup", sign_in: "login", sign_out: "logout" },
             controllers: { sessions: "users/sessions",
                            passwords: "users/passwords",
                            registrations: "users/registrations",
                            confirmations: "users/confirmations" }

  namespace :v1 do
    # TODO: make API endpoints for future mobile development
  end

  resource :user, only: :show
  resources :words, only: :index
  resources :definitions, only: %i[new create edit update destroy] do
    resources :votes, only: :create, module: :definitions
  end
  resources :tags, only: %i[index show]
  resources :unknown_words, only: %i[index new create]

  get "initials/:initial", to: "initials#show", constraints: { initial: /\w/ }, as: :initial

  root to: "words#index"
end

app/views/layouts/_footer.html.slim
footer
  .container
    .row[style="padding:3rem 0"]
      / popular definitions
      .col-md-4.mb-4
        .text-light.h5 Popular Definitions
        ul.list-group
          - Definition.popular(5).each do |definition|
            li.list-group-item
               = active_link_to words_path(q: definition.word), active: :exact, active_disable: true do
                = definition.word
                .badge.badge-secondary.ml-1 = definition.score
                .text-muted.d-inline
                  = " - "
                  small = truncate(definition.definition, length: 70)
        .mt-1
          = active_link_to "Create Definition", new_definition_path, active: :exact, active_disable: true,  class: "text-light"

      / undefined words
      .col-md-4.mb-4
        .text-light.h5 Undefined Words
        ul.list-group
          - UnknownWord.limit(10).each do |unknown_word|
            li.list-group-item
              = active_link_to unknown_word.word, new_definition_path(word: unknown_word.word), active: :exact, active_disable: true
              - if unknown_word.memo.present?
                .text-muted.d-inline
                  = " - "
                  small = truncate(unknown_word.memo, length: 70)

        .mt-1
          = active_link_to "Register Undefined Word", new_unknown_word_path, active: :exact, active_disable: true, class: "text-light"
          br/
          = active_link_to "All Undefined Words", unknown_words_path, active: :exact, active_disable: true, class: "text-light"

      / top contributers
      .col-md-4.mb-4
        .text-light.h5 Top Contributors
        ul.list-group
          - Definition.author_contribution_hash.take(10).each do |id, score|
            li.list-group-item
              = User.find(id).email.split("@").first
              .badge.badge-secondary.ml-1 = score
        .mt-1
          = active_link_to "Contribute", unknown_words_path, active: :exact, active_disable: true, class: "text-light"

app/views/layouts/_top_nav.html.slim
.bg-white.border-bottom.shadow-sm.fixed-top
  .container-fluid
    .d-flex.justify-content-between
      = yield(:top_left_link).presence || (link_to "Search", root_path).html_safe

      nav
        - if user_signed_in?
          span.dropdown.p-2.text-dark
            a#TopNav-userDropdown.dropdown-toggle[aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"]
              = current_user.email
            .dropdown-menu.dropdown-menu-right[aria-labelledby="TopNav-userDropdown"]
              - if current_user.admin?
                = active_link_to "Admin Dashboard", admin_root_path, active: :exact, active_disable: true, class: "dropdown-item"
              = active_link_to "Log Out", destroy_user_session_path, method: :delete, active: :exact, active_disable: true, class: "dropdown-item"
        - else
          = active_link_to "Log In", new_user_session_path, method: :post, active: :exact, active_disable: true, class: "p-2 text-dark"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title yield(:title)
    = csrf_meta_tags
    = csp_meta_tag
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"]
    meta[http-equiv="Accept-CH" content="DPR, Viewport-Width, Width"]

    / Keep track of vote counts
    meta[data-upvotes="#{current_user&.upvotes&.join(',')}"]
    meta[data-downvotes="#{current_user&.downvotes&.join(',')}"]

    = favicon_link_tag asset_path('favicon.png')

    / from asset pipeline
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    / from webpacker
    / = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  ruby:
    body_data = { action: action_name.dasherize, controller: controller_path.parameterize.dasherize }
    body_data.merge!(logged_in: true) if current_user
    body_data.merge!(admin: true) if current_user&.admin?
  = content_tag :body, data: body_data do
    = render 'layouts/top_nav'
    main.container
      = flash_tag
      = yield
    = render 'layouts/footer'